---

- name: Install dnsmasq package
  yum:
    name={{dnsmasq_pkg_name}}
    state={{dnsmasq_pkg_state}}

- name: template dnsmasq.conf
  template:
    src={{ansible_os_family}}-{{ansible_distribution_major_version}}-dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
    owner=root
    group=root
    mode=0644
  notify: svc restart dnsmasq

- name: ensure tftproot exists
  file:
    path={{dnsmasq_tftproot}}
    state=directory
    owner=root
    group=root
    mode=0755
  when: dnsmasq_tftp is defined and dnsmasq_tftp

- name: start, enable svc
  service:
    name={{dnsmasq_svc_name}}
    state={{dnsmasq_svc_state}}
    enabled={{dnsmasq_svc_enabled}}

